name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    container: pspdev/pspdev:latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add zip

    - name: Checkout apollo-lib
      uses: actions/checkout@v4
      with:
        repository: bucanero/apollo-lib
        path: apollo-lib

    - name: Checkout dbglogger
      uses: actions/checkout@v4
      with:
        repository: bucanero/dbglogger
        path: dbglogger

    - name: Get short SHA
      id: slug
      run: |
        printf '%s\n' "sha8=$(printf '%s\n' ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make -f Makefile.psp install

    - name: Install apollo-lib
      working-directory: apollo-lib
      run: |
        make -f Makefile.psp install

    - name: Build Apollo App Package
      run: |
        psp-cmake . -DCMAKE_BUILD_TYPE=Release
        make
        make createzip

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: apollo-psp-build_${{ steps.slug.outputs.sha8 }}
        path: apollo-psp.zip
        if-no-files-found: error
